#!/bin/bash

docker ps -a | awk '{ print $1}' | grep -v 'CONTAINER' | xargs docker stop
docker ps -a | awk '{ print $1}' | grep -v 'CONTAINER' | xargs docker rm
docker images | awk '{ print $3 }' | grep -v 'IMAGE' | xargs docker rmi
